### ISSUE TITLE
build.rs errors on Windows

### ISSUE THREAD

**Issue by maxammann** [elbiazo/tinyinst-rs#1]
I'm checking out LibAFL and running `rust-analyzer`. It seems like this package is raising some errors:

```
--- stdout
  cargo:warning=Pulling TinyInst from github
  cargo:warning=Generating Bridge files.

  C:\Users\Max\.cargo\git\checkouts\tinyinst-rs-ac5c53260d70f4ec\3eaad69>git clone git@github.com:elbiazo/TinyInst.git 

  C:\Users\Max\.cargo\git\checkouts\tinyinst-rs-ac5c53260d70f4ec\3eaad69>pushd TinyInst 

  C:\Users\Max\.cargo\git\checkouts\tinyinst-rs-ac5c53260d70f4ec\3eaad69\TinyInst>git submodule update --init --recursive 

  C:\Users\Max\.cargo\git\checkouts\tinyinst-rs-ac5c53260d70f4ec\3eaad69\TinyInst>popd

  --- stderr
  fatal: destination path 'TinyInst' already exists and is not an empty directory.
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\Max\.cargo\git\checkouts\tinyinst-rs-ac5c53260d70f4ec\3eaad69\build.rs:31:10
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
     1: core::panicking::panic_fmt
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
     2: core::result::unwrap_failed
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\result.rs:1785
     3: enum2$<core::result::Result<std::process::ExitStatus,std::io::error::Error> >::unwrap<std::process::ExitStatus,std::io::error::Error>
               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\result.rs:1107
     4: build_script_build::main
               at .\build.rs:27
     5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops\function.rs:248
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by elbiazo** [comment]
I seen this error before. Couldn't reproduce it but i got around it by deleting the folder that contains Tinyinst.

**Comment by maxammann** [comment]
I think we should add code do handle this. Either use the existing one or remove the existing one if it is stored in target/.

What do you think?

**Comment by elbiazo** [comment]
i think thats good idea! i do wonder why it happens. I couldn't reproduce it so.

**Comment by elbiazo** [comment]
project have been moved under official aflplusplus. This [issue](https://github.com/AFLplusplus/tinyinst-rs/issues/2) will fix this.
